In [1]:
import openpyxl as oxl
import json

In [2]:
path = 'pokemon_db.xlsx'
wb = oxl.load_workbook(path)

In [3]:
sheet = wb.active

In [4]:
pokemon_data = []
for row_index in range (len(sheet['A'])):
    if sheet[row_index+1][0] == "Nama":
        continue

    pokemon = {}
    pokemon['Name']=sheet[row_index+1][0].value
    pokemon['Type']=sheet[row_index+1][1].value
    pokemon['Total']=sheet[row_index+1][2].value
    pokemon['HP']=sheet[row_index+1][3].value
    pokemon['Attack']=sheet[row_index+1][4].value
    pokemon['Defense']=sheet[row_index+1][5].value
    pokemon['Sp.Atk']=sheet[row_index+1][6].value
    pokemon['Sp.Def']=sheet[row_index+1][7].value
    pokemon['Speed']=sheet[row_index+1][8].value

    pokemon_data.append(pokemon)

In [5]:
with open('hanif.uxlearn.json', 'w') as f:
    json.dump(pokemon_data, f)

In [6]:
import pandas as pd
pokes = pd.DataFrame(pokemon_data)
pokes

,Name,Type,Total,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed
0,Name,Type,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
1,Diglett,Ground,265,10,55,25,35,45,95
2,Diglett Alolan Diglett,Ground Steel,265,10,55,30,35,45,90
3,Dugtrio,Ground,425,35,100,50,50,70,120
4,Dugtrio Alolan Dugtrio,Ground Steel,425,35,100,60,50,70,110
...,...,...,...,...,...,...,...,...,...
967,Eternatus Eternamax,Poison Dragon,1125,255,115,250,125,250,130
968,Kubfu,Fighting,385,60,90,60,53,50,72
969,Urshifu Single Strike Style,Fighting Dark,550,100,130,100,63,60,97
970,Urshifu Rapid Strike Style,Fighting Water,550,100,130,100,63,60,97
971,Zarude,Dark Grass,600,105,120,105,70,95,105