In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
alamat = 'https://en.wikipedia.org/wiki/Comparison_of_text_editors'
html = urlopen(alamat)
data = BeautifulSoup(html, 'html.parser')

In [3]:
table = data.findAll('table', {'class':'wikitable'})[1]

In [4]:
rows = table.findAll('tr')

In [5]:
csvRows = []
for row in rows:
    csvRow = []
    for cell in row.findAll(['td','th']):
        csvRow.append(cell.get_text())
    csvRows.append(csvRow)

In [6]:
csvRows = pd.DataFrame(csvRows)

In [7]:
csvRows

,0,1,2,3,4,5,6
0,\n,Microsoft Windows\n,macOS\n,Linux\n,BSD\n,Unix\n,OpenVMS\n
1,Acme\n,Partial[3]\n,\n,\n,\n,\n,\n
2,AkelPad\n,\n,\n,\n,\n,\n,\n
3,Alphatk\n,\n,\n,\n,\n,\n,\n
4,Aquamacs\n,\n,\n,\n,\n,\n,\n
...,...,...,...,...,...,...,...
62,Ulysses (text editor)\n,\n,\n,\n,\n,\n,\n
63,vi\n,\n,\n,\n,\n,\n,\n
64,Vim\n,\n,\n,\n,\n,\n,\n
65,Visual Studio Code\n,\n,\n,\n,?\n,?\n,?\n
66,XEmacs\n,\n,\n,\n,\n,\n,\n

In [8]:
new_header = csvRows.iloc[0]
new_header

0                     \n
1    Microsoft Windows\n
2                macOS\n
3                Linux\n
4                  BSD\n
5                 Unix\n
6              OpenVMS\n
Name: 0, dtype: object

In [10]:
csvRows = csvRows[0]

In [11]:
csvRows

0                          \n
1                      Acme\n
2                   AkelPad\n
3                   Alphatk\n
4                  Aquamacs\n
               ...
62    Ulysses (text editor)\n
63                       vi\n
64                      Vim\n
65       Visual Studio Code\n
66                   XEmacs\n
Name: 0, Length: 67, dtype: object

In [18]:
csvAlts = []
for row in rows:
    csvAlt = []
    for img in row.findAll('img', alt=True):
        csvAlt.append(img['alt'])
    csvAlts.append(csvAlt)

In [19]:
csvAlts

[[],
 ['Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['No', 'Yes', 'No', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['No', 'Yes', 'No', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'Yes', 'Yes', 'No', 'No', 'No'],
 ['No', 'Yes', 'No', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['No', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['No', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'],
 ['Yes', 'Yes', 'Yes', 'No', 'Yes', 'No'],
 ['No', 'Yes', 'No', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['No', 'Yes', 'No', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes', 'No', 'No', 'No'],
 ['No', 'Yes', 'No', 'No', 'No', 'No'],
 ['No', 'Yes', 'No', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['No', 'Yes', 'No', 'No', 'No', 'No'],
 ['Yes', 'No', 'No', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes', 'No', 'No', 'No'],
 ['No', 'Yes', 'No', 'No', 'No', 'No'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'],
 ['Yes', 'Yes', 'Yes'],
 ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes']]

In [20]:
csvAlts = pd.DataFrame(csvAlts)

In [21]:
csvAlts

       0     1     2     3     4     5
0   None  None  None  None  None  None
1    Yes   Yes   Yes   Yes    No  None
2    Yes    No    No    No    No    No
3    Yes   Yes   Yes   Yes   Yes   Yes
4     No   Yes    No    No    No    No
..   ...   ...   ...   ...   ...   ...
62    No   Yes    No    No    No    No
63   Yes   Yes   Yes   Yes   Yes   Yes
64   Yes   Yes   Yes   Yes   Yes   Yes
65   Yes   Yes   Yes  None  None  None
66   Yes   Yes   Yes   Yes   Yes   Yes

[67 rows x 6 columns]

In [22]:
csvRows = pd.DataFrame(csvRows)

In [23]:
csvRows

                          0
0                        \n
1                    Acme\n
2                 AkelPad\n
3                 Alphatk\n
4                Aquamacs\n
..                      ...
62  Ulysses (text editor)\n
63                     vi\n
64                    Vim\n
65     Visual Studio Code\n
66                 XEmacs\n

[67 rows x 1 columns]

In [24]:
result = pd.concat([csvRows, csvAlts], axis=1, sort=False)

In [25]:
result

                          0     0     1     2     3     4     5
0                        \n  None  None  None  None  None  None
1                    Acme\n   Yes   Yes   Yes   Yes    No  None
2                 AkelPad\n   Yes    No    No    No    No    No
3                 Alphatk\n   Yes   Yes   Yes   Yes   Yes   Yes
4                Aquamacs\n    No   Yes    No    No    No    No
..                      ...   ...   ...   ...   ...   ...   ...
62  Ulysses (text editor)\n    No   Yes    No    No    No    No
63                     vi\n   Yes   Yes   Yes   Yes   Yes   Yes
64                    Vim\n   Yes   Yes   Yes   Yes   Yes   Yes
65     Visual Studio Code\n   Yes   Yes   Yes  None  None  None
66                 XEmacs\n   Yes   Yes   Yes   Yes   Yes   Yes

[67 rows x 7 columns]

In [28]:
df = result[1:]
df.columns = ['Text Editor', 'Microsoft Windows', 'macOS', 'Linux', 'BSD', 'Unix', 'OpenVMS']

In [29]:
df

                Text Editor Microsoft Windows macOS Linux   BSD  Unix OpenVMS
1                    Acme\n               Yes   Yes   Yes   Yes    No    None
2                 AkelPad\n               Yes    No    No    No    No      No
3                 Alphatk\n               Yes   Yes   Yes   Yes   Yes     Yes
4                Aquamacs\n                No   Yes    No    No    No      No
5                    Atom\n               Yes   Yes   Yes    No    No      No
..                      ...               ...   ...   ...   ...   ...     ...
62  Ulysses (text editor)\n                No   Yes    No    No    No      No
63                     vi\n               Yes   Yes   Yes   Yes   Yes     Yes
64                    Vim\n               Yes   Yes   Yes   Yes   Yes     Yes
65     Visual Studio Code\n               Yes   Yes   Yes  None  None    None
66                 XEmacs\n               Yes   Yes   Yes   Yes   Yes     Yes

[66 rows x 7 columns]